import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["./main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/closebrackets",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/comment",
		"@codemirror/fold",
		"@codemirror/gutter",
		"@codemirror/highlight",
		"@codemirror/history",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/matchbrackets",
		"@codemirror/panel",
		"@codemirror/rangeset",
		"@codemirror/rectangular-selection",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/stream-parser",
		"@codemirror/text",
		"@codemirror/tooltip",
		"@codemirror/view",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

// Custom copy function
function copyToDist() {
    const distDir = "markdown-to-pdf-mobile";
    if (!fs.existsSync(distDir)) {
        fs.mkdirSync(distDir);
    }
    fs.copyFileSync("main.js", path.join(distDir, "main.js"));
    fs.copyFileSync("manifest.json", path.join(distDir, "manifest.json"));
	if (fs.existsSync("styles.css")) {
		fs.copyFileSync("styles.css", path.join(distDir, "styles.css"));
	}
    console.log("Copied artifacts to " + distDir);
}

if (prod) {
	await context.rebuild();
    copyToDist();
	process.exit(0);
} else {
	await context.watch();
    // In watch mode, we might want to hook into build end, but esbuild watch is persistent.
    // For now, simple dev execution.
    copyToDist();
}
